BUILD_TYPE=load

PROJECT_NAME=loadblink
ASM_SOURCES=blink.s
COMMON_DEPS=led.o utils.o

# PROJECT_NAME=loadsnes
# ASM_SOURCES=snes.s
# COMMON_DEPS=snes.o zeropage.o console.o utils.o

C_SOURCES=

LCD_TYPE=20

include ../common/makefile