.globalzp sp
.globalzp sreg
.globalzp regsave

.globalzp tmp1
.globalzp tmp2
.globalzp tmp3
.globalzp tmp4
.globalzp tmp5
.globalzp ptr1
.globalzp ptr2
.globalzp ptr3
.globalzp ptr4

.globalzp console_out_ptr
.globalzp lcd_out_ptr

.globalzp zp_sd_address
.globalzp zp_sd_currentsector
.globalzp fat32_fatstart
.globalzp fat32_datastart
.globalzp fat32_rootcluster
.globalzp fat32_sectorspercluster
.globalzp fat32_pendingsectors
.globalzp fat32_address
.globalzp fat32_nextcluster
.globalzp fat32_bytesremaining
.globalzp fat32_errorstage
.globalzp fat32_filenamepointer


.globalzp DPL
.globalzp DPH

.globalzp CNT

