PROJECT_NAME=system1

ASM_SOURCES=main.s
C_SOURCES=
COMMON_DEPS=via.o led.o lcd.o utils.o console.o zeropage.o strings.o modem2.o debug.o keyboard.o spi.o sdcard.o fat32.o rtc.o

include ../common/makefile